#Crontab is used for scheduling the jobs etc. When we want to achieve specific tasks at a particular time. It was also used in jenkins and github to schedule the jobs by looking at particular intervals for new commits etc.
#Every minute use image busybox, create a pod and go to shell script and execute the command to print the current time and a hello message every minute. A job will be created for it.
#Use command to see cron-jobs : kubectl get cronjobs
#Use the command to delete cron-jobs : kubectl delete cronjobs <jobname>
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
