#TO keep a secret file for id and password. Opaque means not visible.
#To check secrets : kubectl get secrets
#To check the secrets file : kubectl get secrets -o yaml 
#secrets is used in ansible also.
apiVersion: v1
kind: Secret
metadata:
  name: tomcat-pass
type: Opaque
stringData:
   password: admin123
   username: admin

