#It will create a pod from jenkins image. It will give custom CPU limits to the container being run from this script.
#To view the specification of the pods: kubectl describe pod <podname>
apiVersion: v1
kind: Pod
metadata:
  name: springpeople-cpu
spec:
  containers:
  - name: springpeople-container
    image: jenkins/jenkins
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
